

elements = {"username_textbox": ".//*[@id='input_0']",
            "password_textbox": ".//*[@id='input_1']",
            "login_button":"//html/body/div[1]/md-whiteframe/md-content/form/div[4]/button",

            "machines_link": ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/div[2]/p[1]/a",
            "machines_pic": ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/div[2]/p[2]/a/img",
            "machines_label": ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/div[2]/div",

            "defense_shield_link": ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/div[4]/p[1]/a",
            "defense_shield_pic": ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/div[4]/p[2]/a/img",
            "defense_shield_label": ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/div[4]/div",

            "logout_button": ".//*[@id='wrap']/div/tour/div[1]/div[1]/div/ul/li[1]/a/span",
            "error_message": "//html/body/div[1]/md-whiteframe/md-content/form/div[2]/div",
            "user_search":".//*[@id='table_system_user_filter']/label/input",
            "user_table_first_element":".//*[@id='table_system_user']/tbody/tr/td[1]/a",
            "user_action":"html/body/div[2]/div/div/div[1]/button",
            "user_delete":"html/body/div[2]/div/div/div[1]/ul/li[2]/a",
            "user_delete_confirm":".//*[@id='action-Delete']/div/div[3]/button[2]",
            "user_group":".//*[@id='createuser']/div/div[2]/div[3]/div[4]/label[%d]",
            "accounts":".//*[@id='collapse-2']/li[1]/a",
            "add_account":"html/body/div[2]/div/div/a",
            "create_account":".//*[@id='createaccountLabel']",
            "account_name":".//*[@id='createaccount']/div/div[2]/div[3]/div[1]/input",
            "account_username":".//*[@id='createaccount']/div/div[2]/div[3]/div[2]/input",
            "account_confirm":".//*[@id='createaccount']/div/div[3]/button[2]",
            "account_table_first_element":".//*[@id='table_cloudbroker_account']/tbody/tr[1]/td[2]",
            "account_search" : ".//*[@id='table_cloudbroker_account_filter']/label/input",
            "account_first_id":".//*[@id='table_cloudbroker_account']/tbody/tr[1]/td[1]",
            "add_cloudspace":"html/body/div[2]/div/div/a[2]",
            "create_cloud_space":".//*[@id='create_spaceLabel']",
            "account_first_user_name":"html/body/div[2]/div/div/table[3]/tbody/tr/td[1]/a",
            "cloud_space_user_name":"account_first_user_name",
            "cloud_space_confirm":".//*[@id='create_space']/div/div[3]/button[2]",
            "cloud_space_search":".//*[@id='table_cloudbroker_cloudspace_filter']/label/input",
            "cloud_space_table_first_element_2":".//*[@id='table_cloudbroker_cloudspace']/tbody/tr/td[2]",
            "cloud_space_table_first_element_1":".//*[@id='table_cloudbroker_cloudspace']/tbody/tr/td[1]/a",
            "cloud_spaces":".//*[@id='collapse-2']/li[2]/a",
            "cloudspace_first_id":""
            }