elements = {'storage_menu': 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[5]', 'google': ".//*[@id='lst-ib']",
            'grid_sub_ec': ".//*[@id='collapse-4']/li[2]/a", 'cloudbroker_sub_cs': ".//*[@id='collapse-2']/li[2]/a",
            'grid_text': 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[4]/ul[1]/a[2]',
            'cloudbroker_sub_locations': ".//*[@id='collapse-2']/li[3]/a",
            'ays_text': 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[1]/ul[1]/a[2]',
            'username': ".//*[@id='createuser']/div/div[2]/div[3]/div[1]/input",
            'virtual_machine_delete': 'html/body/div[2]/div/div/div[1]/ul/li[4]/a',
            'machines_link': ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/div[2]/p[1]/a",
            'account_first_user_name': 'html/body/div[2]/div/div/table[3]/tbody/tr/td[1]/a',
            'username_textbox': ".//*[@id='input_0']",
            'cloud_space_confirm': ".//*[@id='create_space']/div/div[3]/button[2]",
            'machine_images_list': ".//*[@id='createmachine']/div/div[2]/div[3]/div[4]/select",
            'password': ".//*[@id='createuser']/div/div[2]/div[3]/div[3]/input",
            'create_cloud_space': ".//*[@id='create_spaceLabel']",
            'login_button': '//html/body/div[1]/md-whiteframe/md-content/form/div[4]/button',
            'system_sub_ao': ".//*[@id='collapse-6']/li[9]/a",
            'user_table_first_element': ".//*[@id='table_system_user']/tbody/tr/td[1]/a",
            'machine_confirm_button': ".//*[@id='createmachine']/div/div[3]/button[2]",
            'statistics': 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[3]/ul/a',
            'cloud_spaces': ".//*[@id='collapse-2']/li[2]/a",
            'account_username': ".//*[@id='createaccount']/div/div[2]/div[3]/div[2]/input",
            'account_search': ".//*[@id='table_cloudbroker_account_filter']/label/input",
            'account_delete': 'html/body/div[2]/div/div/div[1]/ul/li[4]/a',
            'defense_shield_label': ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/div[4]/div",
            'system_text': 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[6]/ul[1]/a[2]',
            'add_cloudspace': 'html/body/div[2]/div/div/a[2]', 'grid_sub_jq': ".//*[@id='collapse-4']/li[4]/a",
            'grid_sub_audits': ".//*[@id='collapse-4']/li[1]/a", 'system_sub_pl': ".//*[@id='collapse-6']/li[8]/a",
            'cloudbroker_sub_users': ".//*[@id='collapse-2']/li[8]/a", 'grid_sub_vm': ".//*[@id='collapse-4']/li[9]/a",
            'ays_arrow': 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[1]/ul[1]/a[1]',
            'cloudbroker_sub_private_nw': ".//*[@id='collapse-2']/li[7]/a",
            'user_delete': 'html/body/div[2]/div/div/div[1]/ul/li[2]/a',
            'machines_pic': ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/div[2]/p[2]/a/img",
            'ays_sub_service': ".//*[@id='collapse-1']/li[1]/a",
            'cloud_space_table_first_element_1': ".//*[@id='table_cloudbroker_cloudspace']/tbody/tr/td[1]/a",
            'accounts': ".//*[@id='collapse-2']/li[1]/a", 'system_sub_api': ".//*[@id='collapse-6']/li[7]/a",
            'virtual_machine_action': 'html/body/div[2]/div/div/div[1]/button',
            'virtual machine search': ".//*[@id='table_cloudbroker_vmachine_filter']/label/input",
            'cloudspace_delete': 'html/body/div[2]/div/div/div[1]/ul/li[2]/a',
            'cloud_broker': 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[2]/ul[1]/a[2]',
            'grid_arrow': 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[4]/ul[1]/a[1]',
            'account_name': ".//*[@id='createaccount']/div/div[2]/div[3]/div[1]/input",
            'system_sub_spaces': ".//*[@id='collapse-6']/li[1]/a",
            'cloudspace_delete_reason': ".//*[@id='action-DeleteCloudSpace']/div/div[2]/div[3]/div/input",
            'virtual_machine_page_status': 'html/body/div[2]/div/div/table[1]/tbody/tr[12]/td[2]',
            'grid_sub_gn': ".//*[@id='collapse-4']/li[7]/a", 'user_action': 'html/body/div[2]/div/div/div[1]/button',
            'left_menu_button': ".//*[@id='PortalsHamburgerMenu']",
            'cloudbroker_sub_vm': ".//*[@id='collapse-2']/li[10]/a", 'storage_sub_1': ".//*[@id='collapse-5']/li/a",
            'system_menu': 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[6]',
            'grid_sub_jobs': ".//*[@id='collapse-4']/li[3]/a",
            'user_search': ".//*[@id='table_system_user_filter']/label/input",
            'system_sub_code': ".//*[@id='collapse-6']/li[6]/a", 'add_user': 'html/body/div[2]/div/div/a',
            'system_sub_users': ".//*[@id='collapse-6']/li[4]/a", 'create_account': ".//*[@id='createaccountLabel']",
            'system_arrow': 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[6]/ul[1]/a[1]',
            'ays_menu': 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[1]',
            'system_sub_groups': ".//*[@id='collapse-6']/li[5]/a",
            'virtual_machine_delete_reason': ".//*[@id='action-Delete']/div/div[2]/div[3]/div/input",
            'create_virtual_machine_on_cpu_node': ".//*[@id='createmachineLabel']",
            'account_first_id': ".//*[@id='table_cloudbroker_account']/tbody/tr[1]/td[1]/a",
            'cloud_space_table_first_element_2': ".//*[@id='table_cloudbroker_cloudspace']/tbody/tr/td[2]",
            'user_group': ".//*[@id='createuser']/div/div[2]/div[3]/div[4]/label[%d]",
            'end_user_home': ".//*[@id='navbar-list']/ul[1]/li[1]/a",
            'cloudbroker_sub_public_nw': ".//*[@id='collapse-2']/li[6]/a",
            'machine_memory_list': ".//*[@id='createmachine']/div/div[2]/div[3]/div[5]/select",
            'storage_arrow': 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[5]/ul[1]/a[1]',
            'grid_sub_so': ".//*[@id='collapse-4']/li[8]/a",
            'cloudbroker_text': 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[2]/ul[1]/a[2]',
            'account_action': 'html/body/div[2]/div/div/div[1]/button',
            'machines_label': ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/div[2]/div",
            'add_virtual_machine': 'html/body/div[2]/div/div/a[3]',
            'defense_shield_pic': ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/div[4]/p[2]/a/img",
            'ays_sub_templates': ".//*[@id='collapse-1']/li[2]/a",
            'left_menu': 'html/body/div[1]/div/div[1]/div/nav/div',
            'users': ".//*[@id='collapse-2']/li[8]/a",
            'cloudspace_delete_confirm': ".//*[@id='action-DeleteCloudSpace']/div/div[3]/button[2]",
            'virtual_machine_delete_confirm': ".//*[@id='action-Delete']/div/div[3]/button[2]",
            'grid_sub_jumpsacale': ".//*[@id='collapse-4']/li[5]/a",
            'error_message': '//html/body/div[1]/md-whiteframe/md-content/form/div[2]/div',
            'username_search': ".//*[@id='table_system_user_filter']/label/input",
            'machine_disk_list': ".//*[@id='createmachine']/div/div[2]/div[3]/div[6]/select",
            'system_sub_sm': ".//*[@id='collapse-6']/li[3]/a",
            'virtual_machine_tabkle_first_element_2': ".//*[@id='table_cloudbroker_vmachine']/tbody/tr/td[2]",
            'cloudspace_page_status': 'html/body/div[2]/div/div/table[1]/tbody/tr[6]/td[2]',
            'machine_name': ".//*[@id='createmachine']/div/div[2]/div[3]/div[1]/input",
            'logout_button': ".//*[@id='wrap']/div/tour/div[1]/div[1]/div/ul/li[1]/a/span",
            'mail': ".//*[@id='createuser']/div/div[2]/div[3]/div[2]/input",
            'storage_text': 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[5]/ul[1]/a[2]',
            'defense_shield_link': ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/div[2]/div[4]/p[1]/a",
            'user_delete_confirm': ".//*[@id='action-Delete']/div/div[3]/button[2]",
            'account_page_status': 'html/body/div[2]/div/div/table[1]/tbody/tr[2]/td[2]',
            'account_confirm': ".//*[@id='createaccount']/div/div[3]/button[2]",
            'cloud_space_search': ".//*[@id='table_cloudbroker_cloudspace_filter']/label/input",
            'add_account': 'html/body/div[2]/div/div/a',
            'username_table_first': ".//*[@id='table_system_user']/tbody/tr[1]/td[1]/a",
            'machine_description': ".//*[@id='createmachine']/div/div[2]/div[3]/div[2]/input",
            'grid_sub_logs': ".//*[@id='collapse-4']/li[6]/a",
            'grid_menu': 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[4]', 'password_textbox': ".//*[@id='input_1']",
            'virtual_machine_table_first_element': ".//*[@id='table_cloudbroker_vmachine']/tbody/tr/td[1]/a",
            'confirm_add_user': ".//*[@id='createuser']/div/div[3]/button[2]",
            'cloudbroker_arrow': 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[2]/ul[1]/a[1]',
            'cloud_space_name': ".//*[@id='create_space']/div/div[2]/div[3]/div[1]/input",
            'cloud_space_user_name': ".//*[@id='create_space']/div/div[2]/div[3]/div[2]/input",
            'cloudbroker_sub_groups': ".//*[@id='collapse-2']/li[9]/a",
            'cloudbroker_sub_sv': ".//*[@id='collapse-2']/li[11]/a", 'create_user': ".//*[@id='createuserLabel']",
            'system_sub_sc': ".//*[@id='collapse-6']/li[2]/a",
            'account_delete_reason': ".//*[@id='action-Delete']/div/div[2]/div[3]/div/input",
            'cloudbroker_menu': 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[2]',
            'cloudspace_action': 'html/body/div[2]/div/div/div[1]/button',
            'cloudbroker_sub_stacks': ".//*[@id='collapse-2']/li[4]/a",
            'cloudbroker_sub_images': ".//*[@id='collapse-2']/li[5]/a",
            'account_delete_confirm': ".//*[@id='action-Delete']/div/div[3]/button[2]",
            'end_user': 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[7]/ul/a',
            'account_table_first_element': ".//*[@id='table_cloudbroker_account']/tbody/tr[1]/td[2]",
            'cloudbroker_sub_accounts': ".//*[@id='collapse-2']/li[1]/a",
            'cloudbroker': 'html/body/div[1]/div/div[1]/div/nav/div/ul/li[2]/ul[1]/a[1]',
            'ec_table_no_data_text': ".//*[@id='DataTables_Table_0']/tbody/tr/td", 'ec_table_header1': '',
            'error_conditions_header2': 'html/body/div[2]/div/div/h2',
            'grid_portal_header1': 'html/body/div[2]/div/div/ul/li[1]',
            'action_purge_select': ".//*[@id='action-Purge']/div/div[2]/div[3]/div/select",
            'ec_table_header5': ".//*[@id='DataTables_Table_0']/thead/tr/th[5]",
            'purge_button': 'html/body/div[2]/div/div/div[1]/ul/li/a',
            'Error_Conditions': ".//*[@id='collapse-4']/li[2]/a",
            'entries_select_option1': ".//*[@id='DataTables_Table_0_length']/label/select/option[1]",
            'entries_select': ".//*[@id='DataTables_Table_0_length']/label/select",
            'ec_table_header3': ".//*[@id='DataTables_Table_0']/thead/tr/th[3]",
            'ec_entries_info': ".//*[@id='DataTables_Table_0_info']",
            'error_conditions_header1': 'html/body/div[2]/div/div/ul/li[2]',
            'ec_action_button': 'html/body/div[2]/div/div/div[1]/button',
            'ec_table_header7': ".//*[@id='DataTables_Table_0']/thead/tr/th[7]",
            'ec_table_header2': ".//*[@id='DataTables_Table_0']/thead/tr/th[2]",
            'action_purge_confirm_button': ".//*[@id='action-Purge']/div/div[3]/button[2]",
            'entries_select_option2': ".//*[@id='DataTables_Table_0_length']/label/select/option[2]",
            'ec_table_body': ".//*[@id='DataTables_Table_0']/tbody",
            'ec_table_header6': ".//*[@id='DataTables_Table_0']/thead/tr/th[6]",
            'ec_table_delete_button': ".//*[@id='DataTables_Table_0']/tfoot/tr/td[1]/button",
            'ALL_option': ".//*[@id='action-Purge']/div/div[2]/div[3]/div/select/option[1]",
            'ec_table_header4': ".//*[@id='DataTables_Table_0']/thead/tr/th[4]",
            'ec_table_row': ".//*[@id='DataTables_Table_0']/tbody/tr[1]",
            'login_popup': 'html/body/div/md-whiteframe/md-toolbar/h2', 'user_name': 'html/body/div[2]/div/div/h2',
            'virtual_machine_table_first_element_2': ".//*[@id='table_cloudbroker_vmachine']/tbody/tr/td[2]",
            'cloudspace_delete_virtual': 'html/body/div[2]/div/div/div[1]/ul/li[3]/a',
            'cloudspace_delete_deployed': 'html/body/div[2]/div/div/div[1]/ul/li[2]/a',
            'ays_menu_': ".//*[@id='collapse-1']/li[1]/a"}
