elements = {
    "google":".//*[@id='lst-ib']",
    "left_menu_button": ".//*[@id='PortalsHamburgerMenu']",
    "left_menu": "html/body/div[1]/div/div[1]/div/nav/div/ul",

    "ays_menu":"html/body/div[1]/div/div[1]/div/nav/div/ul/li[1]",
    "ays_text": "html/body/div[1]/div/div[1]/div/nav/div/ul/li[1]/ul[1]/a[2]",
    "ays_arrow": "html/body/div[1]/div/div[1]/div/nav/div/ul/li[1]/ul[1]/a[1]",
    "ays_sub_service": ".//*[@id='collapse-1']/li[1]/a",
    "ays_sub_templates": ".//*[@id='collapse-1']/li[2]/a",

    "cloudbroker_menu":"html/body/div[1]/div/div[1]/div/nav/div/ul/li[2]",
    "cloudbroker_text": "html/body/div[1]/div/div[1]/div/nav/div/ul/li[2]/ul[1]/a[2]",
    "cloudbroker_arrow": "html/body/div[1]/div/div[1]/div/nav/div/ul/li[2]/ul[1]/a[1]",
    "cloudbroker_sub_accounts": ".//*[@id='collapse-2']/li[1]/a",
    "cloudbroker_sub_cs": ".//*[@id='collapse-2']/li[2]/a",
    "cloudbroker_sub_locations": ".//*[@id='collapse-2']/li[3]/a",
    "cloudbroker_sub_stacks": ".//*[@id='collapse-2']/li[4]/a",
    "cloudbroker_sub_images": ".//*[@id='collapse-2']/li[5]/a",
    "cloudbroker_sub_public_nw": ".//*[@id='collapse-2']/li[6]/a",
    "cloudbroker_sub_private_nw": ".//*[@id='collapse-2']/li[7]/a",
    "cloudbroker_sub_users": ".//*[@id='collapse-2']/li[8]/a",
    "cloudbroker_sub_groups": ".//*[@id='collapse-2']/li[9]/a",
    "cloudbroker_sub_vm": ".//*[@id='collapse-2']/li[10]/a",
    "cloudbroker_sub_sv": ".//*[@id='collapse-2']/li[11]/a",

    "statistics": "html/body/div[1]/div/div[1]/div/nav/div/ul/li[3]/ul/a",

    "grid_menu":"html/body/div[1]/div/div[1]/div/nav/div/ul/li[4]",
    "grid_text": "html/body/div[1]/div/div[1]/div/nav/div/ul/li[4]/ul[1]/a[2]",
    "grid_arrow": "html/body/div[1]/div/div[1]/div/nav/div/ul/li[4]/ul[1]/a[1]",
    "grid_sub_audits": ".//*[@id='collapse-4']/li[1]/a",
    "grid_sub_ec": ".//*[@id='collapse-4']/li[2]/a",
    "grid_sub_jobs": ".//*[@id='collapse-4']/li[3]/a",
    "grid_sub_jq": ".//*[@id='collapse-4']/li[4]/a",
    "grid_sub_jumpsacale": ".//*[@id='collapse-4']/li[5]/a",
    "grid_sub_logs": ".//*[@id='collapse-4']/li[6]/a",
    "grid_sub_gn": ".//*[@id='collapse-4']/li[7]/a",
    "grid_sub_so": ".//*[@id='collapse-4']/li[8]/a",
    "grid_sub_vm": ".//*[@id='collapse-4']/li[9]/a",

    "storage_menu":"html/body/div[1]/div/div[1]/div/nav/div/ul/li[5]",
    "storage_text": "html/body/div[1]/div/div[1]/div/nav/div/ul/li[5]/ul[1]/a[2]",
    "storage_arrow": "html/body/div[1]/div/div[1]/div/nav/div/ul/li[5]/ul[1]/a[1]",
    "storage_sub_1": ".//*[@id='collapse-5']/li/a",

    "system_menu":"html/body/div[1]/div/div[1]/div/nav/div/ul/li[6]",
    "system_text": "html/body/div[1]/div/div[1]/div/nav/div/ul/li[6]/ul[1]/a[2]",
    "system_arrow": "html/body/div[1]/div/div[1]/div/nav/div/ul/li[6]/ul[1]/a[1]",
    "system_sub_spaces": ".//*[@id='collapse-6']/li[1]/a",
    "system_sub_sc": ".//*[@id='collapse-6']/li[2]/a",
    "system_sub_sm": ".//*[@id='collapse-6']/li[3]/a",
    "system_sub_users": ".//*[@id='collapse-6']/li[4]/a",
    "system_sub_groups": ".//*[@id='collapse-6']/li[5]/a",
    "system_sub_code": ".//*[@id='collapse-6']/li[6]/a",
    "system_sub_api": ".//*[@id='collapse-6']/li[7]/a",
    "system_sub_pl": ".//*[@id='collapse-6']/li[8]/a",
    "system_sub_ao": ".//*[@id='collapse-6']/li[9]/a",

    "end_user": "html/body/div[1]/div/div[1]/div/nav/div/ul/li[7]/ul/a",
    "end_user_home":".//*[@id='navbar-list']/ul[1]/li[1]/a"
}
