

elements = {"getting_started_button": ".//*[@id='navbar-list']/ul[2]/li[1]/a",

            "intro_tab": ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/ul/li[1]/a",
            "intro_header_label": ".//*[@id='intro']/div[2]/h2",
            "intro_line1_label": ".//*[@id='intro']/div[2]/p[1]",
            "intro_line2_label": ".//*[@id='intro']/div[2]/p[2]",
            "intro_line3_label": ".//*[@id='intro']/div[2]/ul/li",
            "intro_line4_label": ".//*[@id='intro']/div[2]/p[3]",
            "intro_subheader_label": ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/h2",
            "intro_line5_label": ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/p",
            "intro_spport_link": ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/p/a",

            "cloudspace_tab": ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/ul/li[2]/a",
            "cloudspace_header_label": ".//*[@id='CloudSpace']/div[2]/h2",
            "cloudspace_line1_label": ".//*[@id='CloudSpace']/div[2]/ol/li[1]",
            "cloudspace_line2_label": ".//*[@id='CloudSpace']/div[2]/ol/li[2]",
            "cloudspace_subheader_label": ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/h2",
            "cloudspace_line3_label": ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/p",
            "cloudspace_spport_link": ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/p/a",

            "machines_tab": ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/ul/li[3]/a",
            "machines_header_label": ".//*[@id='MachineDeck']/div[2]/h2",
            "machines_line1_label": ".//*[@id='MachineDeck']/div[2]/ol/li[1]",
            "machines_line2_label": ".//*[@id='MachineDeck']/div[2]/ol/li[2]",
            "machines_line3_label": ".//*[@id='MachineDeck']/div[2]/ol/li[3]",
            "machines_line4_label": ".//*[@id='MachineDeck']/div[2]/ol/li[4]",
            "machines_line5_label": ".//*[@id='MachineDeck']/div[2]/ol/li[5]",
            "machines_line6_label": ".//*[@id='MachineDeck']/div[2]/ol/li[6]",
            "machines_line7_label": ".//*[@id='MachineDeck']/div[2]/ol/li[7]",
            "machines_line8_label": ".//*[@id='MachineDeck']/div[2]/ol/li[8]",
            "machines_line9_label": ".//*[@id='MachineDeck']/div[2]/ol/li[9]",
            "machines_line10_label": ".//*[@id='MachineDeck']/div[2]/ol/li[10]",
            "machines_subheader_label": ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/h2",
            "machines_line11_label": ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/p",
            "machines_spport_link": ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/p/a",

            "defense_shield_tab": ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/ul/li[4]/a",
            "defense_shield_header_label": ".//*[@id='DefenseShield']/div[2]/h2",
            "defense_shield_line1_label": ".//*[@id='DefenseShield']/div[2]/ol/li[1]",
            "defense_shield_line2_label": ".//*[@id='DefenseShield']/div[2]/ol/li[2]",
            "defense_shield_line3_label": ".//*[@id='DefenseShield']/div[2]/ol/li[3]",
            "defense_shield_line4_label": ".//*[@id='DefenseShield']/div[2]/ol/li[4]",
            "defense_shield_line5_label": ".//*[@id='DefenseShield']/div[2]/ol/li[5]",
            "defense_shield_subheader_label": ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/h2",
            "defense_shield_line6_label": ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/p",
            "defense_shield_spport_link": ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/p/a",


            "knowledge_base_button": ".//*[@id='navbar-list']/ul[2]/li[3]/a",
            "knowledge_base_header_label": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/div/div",
            "knowledge_base_line1_tab": ".//*[@id='docs-index-list']/li[1]/a",
            "knowledge_base_line1_tab_header": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/h1",
            "knowledge_base_line1_tab_line1": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/li[1]",
            "knowledge_base_line1_tab_line2": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/li[2]",
            "knowledge_base_line1_tab_line3": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/li[3]",
            "knowledge_base_line1_tab_line4": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/li[4]",
            "knowledge_base_line1_tab_line5": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/li[5]",
            "knowledge_base_line1_tab_line6": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/li[6]",
            "knowledge_base_line1_tab_line7": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/li[7]",
            "knowledge_base_line1_tab_line8": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/li[8]",
            "knowledge_base_line1_tab_line9": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/li[9]",
            "knowledge_base_line1_tab_line10": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/li[10]",
            "knowledge_base_line1_tab_line11": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/li[11]",
            "knowledge_base_line1_tab_line12": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/li[12]",

            "knowledge_base_line2_tab": ".//*[@id='docs-index-list']/li[2]/a",
            "knowledge_base_line2_tab_header": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/h1",
            "knowledge_base_line2_tab_line1": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/li[1]",
            "knowledge_base_line2_tab_line2": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/li[2]",
            "knowledge_base_line2_tab_line3": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/li[3]",
            "knowledge_base_line2_tab_line4": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/li[4]",
            "knowledge_base_line2_tab_line5": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/li[5]",
            "knowledge_base_line2_tab_image5": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/li[5]/img",
            "knowledge_base_line2_tab_line6": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/li[6]",
            "knowledge_base_line2_tab_image6": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/li[6]/img",
            "knowledge_base_line2_tab_line7": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/li[7]",
            "knowledge_base_line2_tab_image7": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/li[7]/img",
            "knowledge_base_line2_tab_line7_sub1": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/ol[1]/li[1]",
            "knowledge_base_line2_tab_line7_sub2": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/ol[1]/li[2]",
            "knowledge_base_line2_tab_line7_sub3": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/ol[1]/li[3]",
            "knowledge_base_line2_tab_line7_image3": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/ol[1]/li[3]/img",
            "knowledge_base_line2_tab_line7_sub4": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/ol[1]/li[4]",
            "knowledge_base_line2_tab_line7_sub5": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/ol[1]/li[5]",
            "knowledge_base_line2_tab_line7_sub6": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/ol[1]/li[6]",
            "knowledge_base_line2_tab_line8": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/li[8]",
            "knowledge_base_line2_tab_image8": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/li[8]/img",
            "knowledge_base_line2_tab_line8_sub1": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/ol[2]/li[1]",
            "knowledge_base_line2_tab_line8_sub2": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/ol[2]/li[2]",
            "knowledge_base_line2_tab_line8_sub3": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/ol[2]/li[3]",
            "knowledge_base_line2_tab_line9": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/li[9]",
            "knowledge_base_line2_tab_line10": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ol/li[10]",

            "knowledge_base_line3_tab": ".//*[@id='docs-index-list']/li[3]/a",
            "knowledge_base_line3_tab_header": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/h1",
            "knowledge_base_line3_tab_line1": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[1]",
            "knowledge_base_line3_tab_image1": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[2]/img",
            "knowledge_base_line3_tab_line2": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[3]",
            "knowledge_base_line3_tab_image2": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[4]/img",
            "knowledge_base_line3_tab_line3": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[5]",
            "knowledge_base_line3_tab_line3_sub1": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ul/li[1]",
            "knowledge_base_line3_tab_line3_sub2": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ul/li[2]",
            "knowledge_base_line3_tab_line3_sub3": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ul/li[3]",
            "knowledge_base_line3_tab_image3": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[6]/img",
            "knowledge_base_line3_tab_image4": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[7]/img",
            "knowledge_base_line3_tab_line4": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[8]",
            "knowledge_base_line3_tab_image5": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[9]/img",
            "knowledge_base_line3_tab_image6": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[10]/img",
            "knowledge_base_line3_tab_line5": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[11]",
            "knowledge_base_line3_tab_line6": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[12]",
            "knowledge_base_line3_tab_line7": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[13]",
            "knowledge_base_line3_tab_line8": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[14]",
            "knowledge_base_line3_tab_line9": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[15]",
            "knowledge_base_line3_tab_image7": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[16]/img",
            "knowledge_base_line3_tab_line10": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[17]",
            "knowledge_base_line3_tab_image8": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[18]/img",
            "knowledge_base_line3_tab_line11": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[19]",
            "knowledge_base_line3_tab_image9": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[20]/img",
            "knowledge_base_line3_tab_line12": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[21]",
            "knowledge_base_line3_tab_image10": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[22]/img",
            "knowledge_base_line3_tab_line13": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[23]",
            "knowledge_base_line3_tab_image11": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[24]/img",
            "knowledge_base_line3_tab_image12": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[25]/img",
            "knowledge_base_line3_tab_image13": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[26]/img",
            "knowledge_base_line3_tab_line14": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[27]",
            "knowledge_base_line3_tab_header1": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/h2[1]",
            "knowledge_base_line3_tab_line15": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[28]",
            "knowledge_base_line3_tab_image14": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[29]/img",
            "knowledge_base_line3_tab_header2": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/h2[2]",
            "knowledge_base_line3_tab_line16": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[30]",
            "knowledge_base_line3_tab_line17": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[31]",

            "knowledge_base_line4_tab": ".//*[@id='docs-index-list']/li[4]/a",
            "knowledge_base_line4_tab_header": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/h1",
            "knowledge_base_line4_tab_line1": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/h3[1]",
            "knowledge_base_line4_tab_text1": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/div[2]/div[1]/textarea",
            "knowledge_base_line4_tab_line2": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/h3[2]",
            "knowledge_base_line4_tab_text2": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/div[3]/div[1]/textarea",
            "knowledge_base_line4_tab_line3": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/h3[3]",
            "knowledge_base_line4_tab_text3": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/div[4]/div[1]/textarea",

            "knowledge_base_line5_tab": ".//*[@id='docs-index-list']/li[5]/a",
            "knowledge_base_line5_tab_header": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/h1",
            "knowledge_base_line5_tab_line1": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[1]",
            "knowledge_base_line5_tab_image1": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[2]/img",
            "knowledge_base_line5_tab_line2": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[3]",
            "knowledge_base_line5_tab_image2": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[4]/img",
            "knowledge_base_line5_tab_line3": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[5]",
            "knowledge_base_line5_tab_line3_sub1": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ul/li[1]",
            "knowledge_base_line5_tab_line3_sub2": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ul/li[2]",
            "knowledge_base_line5_tab_line3_sub3": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/ul/li[3]",
            "knowledge_base_line5_tab_image3": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[6]/img",
            "knowledge_base_line5_tab_image4": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[7]/img",
            "knowledge_base_line5_tab_line4": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[8]",
            "knowledge_base_line5_tab_image5": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[9]/img",
            "knowledge_base_line5_tab_image6": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[10]/img",
            "knowledge_base_line5_tab_line5": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[11]",
            "knowledge_base_line5_tab_line6": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[12]",
            "knowledge_base_line5_tab_line7": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[13]",
            "knowledge_base_line5_tab_line8": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[14]",
            "knowledge_base_line5_tab_line9": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[15]",
            "knowledge_base_line5_tab_image7": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[16]/img",
            "knowledge_base_line5_tab_line10": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[17]",
            "knowledge_base_line5_tab_image8": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[18]/img",
            "knowledge_base_line5_tab_line11": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[19]",
            "knowledge_base_line5_tab_image9": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[20]/img",
            "knowledge_base_line5_tab_line12": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[21]",
            "knowledge_base_line5_tab_image10": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[22]/img",
            "knowledge_base_line5_tab_line13": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[23]",

            "knowledge_base_line6_tab": ".//*[@id='docs-index-list']/li[6]/a",
            "knowledge_base_line6_tab_header": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/h1",
            "knowledge_base_line6_tab_line1": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[1]",
            "knowledge_base_line6_tab_image1": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[2]/img",
            "knowledge_base_line6_tab_line2": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[3]",
            "knowledge_base_line6_tab_image2": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[4]/img",
            "knowledge_base_line6_tab_line3": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[5]",
            "knowledge_base_line6_tab_image3": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[6]/img",
            "knowledge_base_line6_tab_line4": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[7]",
            "knowledge_base_line6_tab_image4": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[8]/img",
            "knowledge_base_line6_tab_line5": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[9]",
            "knowledge_base_line6_tab_image5": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[10]/img",
            "knowledge_base_line6_tab_line6": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[11]",
            "knowledge_base_line6_tab_image6": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[12]/img",
            "knowledge_base_line6_tab_line7": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[13]",
            "knowledge_base_line6_tab_image7": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[14]/img",
            "knowledge_base_line6_tab_line8": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[15]",
            "knowledge_base_line6_tab_image8": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[16]/img",
            "knowledge_base_line6_tab_line9": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[17]",
            "knowledge_base_line6_tab_image9": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[18]/img",
            "knowledge_base_line6_tab_line10": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[19]",
            "knowledge_base_line6_tab_image10": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[20]/img",
            "knowledge_base_line6_tab_line11": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[21]",
            "knowledge_base_line6_tab_image11": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[22]/img",
            "knowledge_base_line6_tab_line12": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[23]",
            "knowledge_base_line6_tab_image12": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[24]/img",
            "knowledge_base_line6_tab_line13": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[25]",
            "knowledge_base_line6_tab_image13": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[26]/img",
            "knowledge_base_line6_tab_line14": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[27]",
            "knowledge_base_line6_tab_image14": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[28]/img",
            "knowledge_base_line6_tab_line15": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[29]",
            "knowledge_base_line6_tab_line16": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[30]",

            "knowledge_base_line7_tab": ".//*[@id='docs-index-list']/li[7]/a",
            "knowledge_base_line7_tab_header": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/h1",
            "knowledge_base_line7_tab_header1": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/h2",
            "knowledge_base_line7_tab_line1": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[1]",
            "knowledge_base_line7_tab_header2": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/h3[1]",
            "knowledge_base_line7_tab_line2": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[2]",
            "knowledge_base_line7_tab_header3": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/h3[2]",
            "knowledge_base_line7_tab_line3": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[3]",
            "knowledge_base_line7_tab_header4": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/h3[3]",
            "knowledge_base_line7_tab_header5": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/h3[4]",
            "knowledge_base_line7_tab_line4": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[4]",
            "knowledge_base_line7_tab_line5": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[5]",
            "knowledge_base_line7_tab_line5_link": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p[5]/a",

            "knowledge_base_subheader_label": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p/strong",
            "knowledge_base_subheader_email": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p/a",
            "knowledge_base_subheader_text": ".//*[@id='wrap']/div/tour/div[2]/div[2]/div/div/div/p",


            "support_button": ".//*[@id='navbar-list']/ul[2]/li[4]/a",
            "support_subheader_label": ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/h1",
            "support_line_label": ".//*[@id='wrap']/div/tour/div[3]/div[2]/div/div/div/a",


            "machine_api_button": ".//*[@id='navbar-list']/ul[2]/li[2]/a",
            "knowlege_base_button": ".//*[@id='navbar-list']/ul[2]/li[3]/a",
            "support_button": ".//*[@id='navbar-list']/ul[2]/li[4]/a",
            "home_button": ".//*[@id='navbar-list']/ul[1]/li[1]/a",
            "machines_button": ".//*[@id='wrap']/div/tour/div[3]/div[1]/ul/li[1]/a",
            "defense_shield_button": ".//*[@id='wrap']/div/tour/div[3]/div[1]/ul/li[2]/a",


            "cloudpsace_menu": ".//*[@id='drop1']/span",


            "logout_button": ".//*[@id='wrap']/div/tour/div[1]/div[2]/div/ul/li[1]/a/span"}